apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: private-sso-tls-cert
  namespace: sso
spec:
  secretName: private-sso-tls
  subject:
    organizations:
    - Open Cluster Management
  usages:
    - server auth
    - client auth
  dnsNames:
    - sso
    - sso.svc
    - sso.svc.cluster.local
    - sso.sso.svc
    - sso.sso.svc.cluster.local
  duration: 720h0m0s
  renewBefore: 168h0m0s
  privateKey:
    algorithm: "RSA"
    size: 2048
  issuerRef:
    name: self-signed-issuer
    kind: ClusterIssuer